#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar
runApplication mpirun -np 4 pimpleFoam -parallel
runApplication reconstructPar
