#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------

wclean libso functionNorm
wclean libso POD
wclean libso Stream

#------------------------------------------------------------------------------
